# Generated by Django 4.2.24 on 2025-09-22 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("kisan_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CropCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(default="🌾", max_length=10)),
            ],
            options={
                "verbose_name_plural": "Crop Categories",
            },
        ),
        migrations.CreateModel(
            name="MarketPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop_name", models.CharField(max_length=100)),
                ("price_per_kg", models.DecimalField(decimal_places=2, max_digits=10)),
                ("market_location", models.CharField(max_length=100)),
                ("date_recorded", models.DateField(auto_now_add=True)),
                ("source", models.CharField(default="Manual Entry", max_length=100)),
            ],
            options={
                "ordering": ["-date_recorded"],
            },
        ),
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("temperature", models.FloatField()),
                ("humidity", models.FloatField()),
                ("rainfall", models.FloatField(default=0.0)),
                ("weather_condition", models.CharField(max_length=50)),
                ("date_recorded", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date_recorded"],
            },
        ),
        migrations.AddField(
            model_name="crop",
            name="actual_harvest_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="crop",
            name="investment_cost",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="crop",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="crop",
            name="planted_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="crop",
            name="status",
            field=models.CharField(
                choices=[
                    ("Planted", "Planted"),
                    ("Growing", "Growing"),
                    ("Ready", "Ready for Harvest"),
                    ("Harvested", "Harvested"),
                    ("Sold", "Sold"),
                ],
                default="Planted",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="farmer",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="farmer",
            name="experience_years",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="farmer",
            name="land_area",
            field=models.DecimalField(
                decimal_places=2, default=0.0, help_text="Area in acres", max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="farmer",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="farmer_profiles/"
            ),
        ),
        migrations.AddField(
            model_name="farmer",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="crop",
            name="season",
            field=models.CharField(
                choices=[
                    ("Kharif", "Kharif (Monsoon)"),
                    ("Rabi", "Rabi (Winter)"),
                    ("Zaid", "Zaid (Summer)"),
                    ("Annual", "Annual"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("harvest_reminder", "Harvest Reminder"),
                            ("price_alert", "Price Alert"),
                            ("weather_alert", "Weather Alert"),
                            ("general", "General"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="kisan_app.farmer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="crop",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="kisan_app.cropcategory",
            ),
        ),
    ]
